DROP TABLE IF EXISTS note;
CREATE TABLE note(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL,
    content TEXT NOT NULL,
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    is_delete INTEGER  DEFAULT 0
);
DROP TABLE IF EXISTS total_info;
CREATE TABLE total_info(
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    total INTEGER DEFAULT 0
);

INSERT INTO total_info VALUES (1,0);